resources:
  repositories:
    - repository: templates
      type: git
      name: pipelines/pipelines



variables:
  - group: general
  - name: version
    value: '0.0.3'

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
       - template: ./templates/build-container-job-linux.yaml@templates
         parameters:
           version: $(version)
           registryUri: $(registryUri)
           registryUsername: $(registryUsername)
           registryPassword: $(registryPassword)
           registryRepository: 'infra'
           imageName: 'skipper-jwt'

